### ISSUE TITLE
Taking it for a spin?

### ISSUE THREAD

**Issue by micahwedemeyer** [weppos/dnsimple-elixir#1]
I'm working on a new project using DNSimple and Elixir, and it led me here. I understand this library is still under development, and that's fine. I'd still like to take it for a spin and see if I can help out with it as I implement things for my project.

Any idea how I go about creating an OAuth app on DNSimple? It looks like this library assumes OAuth bearer tokens, but I can't find anywhere to create an application and get an OAuth token for my account. Is that hidden somewhere behind a beta flag?

I could always try to write something that works with the v1 API, but it would be a shame to take a step backwards when you're already working on an Elixir library for v2.

**Comment by weppos** [comment]
Hi @micahwedemeyer,

> I'm working on a new project using DNSimple and Elixir, and it led me here.

Welcome! I'm glad you are using Elixir, and I'm very glad you are using DNSimple :+1: 

> Any idea how I go about creating an OAuth app on DNSimple? It looks like this library assumes OAuth bearer tokens, but I can't find anywhere to create an application and get an OAuth token for my account. Is that hidden somewhere behind a beta flag?

**Comment by weppos** [comment]
Hi @micahwedemeyer,

> I'm working on a new project using DNSimple and Elixir, and it led me here.

Welcome! I'm glad you are using Elixir, and I'm very glad you are using DNSimple :+1: 

> Any idea how I go about creating an OAuth app on DNSimple? It looks like this library assumes OAuth bearer tokens, but I can't find anywhere to create an application and get an OAuth token for my account. Is that hidden somewhere behind a beta flag?

This client will only support the new version of the DNSimple API, that is currently under development. The first developer preview was released at the end of 2015 and we're currently working towards the public beta.

If you write to support@dnsimple.com I can provide you access to the API v2 Oauth feature. It would be great if you can also provide a little bit more context about what you will be using the API for and what methods you'd expect to use. We still have to port some methods from API v1 to v2, and we can prioritize the work if you have some preference.

> I could always try to write something that works with the v1 API, but it would be a shame to take a step backwards when you're already working on an Elixir library for v2.

I agree, it doesn't make sense to split the effort and create an API v1 client. :smile:

**Comment by micahwedemeyer** [comment]
Sent you an email with my account info,  an overview of my idea, and what API methods I need. I should also say that I'm at a *very* early stage right now. I'm still playing with a bunch of different pieces of the overall puzzle to make sure the idea is even viable.

**Comment by micahwedemeyer** [comment]
Any update? I'd love to get access to the API and start banging around.

**Comment by weppos** [comment]
@micahwedemeyer I replied you almost immediately to you original email, and they yesterday to your follow up. I assume you didn't receive any of the emails.

**Comment by micahwedemeyer** [comment]
No, I haven't received any emails after the original automated "We've received your support request" email. I just added support@dnsimple to my gmail contacts so maybe that will help prevent things from landing in or getting denied.

Glancing at the email headers, I saw this:
`Authentication-Results: mx.google.com;
       spf=softfail (google.com: domain of transitioning SRS0+xVB1=OA=smtp.groovehq.com=bounces+56229-c1a7-email-address-removed@eforward1e.registrar-servers.com does not designate 69.160.33.89 as permitted sender) smtp.mailfrom=SRS0+xVB1=OA=smtp.groovehq.com=bounces+56229-c1a7-email-address-removed@eforward1e.registrar-servers.com;
       dkim=pass header.i=@dnsimple.com;
       dmarc=pass (p=NONE dis=NONE) header.from=dnsimple.com`

It looks like DKIM is passing but SPF is failing. I didn't think an SPF fail caused emails to disappear though.

**Comment by weppos** [comment]
@micahwedemeyer I've resent the email. If you don't receive it let me know, I'll sent it from my account rather than from support.

**Comment by weppos** [comment]
Fixed.
